### ISSUE TITLE
Travis CI tests failing

### ISSUE THREAD

**Issue by onlyurei** [tastejs/todomvc#1683]
Looks like this error has been going on for a while:

``` sh
/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/promise.js:654
    throw error;
    ^
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:46086
    at ClientRequest.<anonymous> (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/http/index.js:375:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From: Task: WebDriver.createSession()
    at acquireSession (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/webdriver.js:107:22)
    at Function.createSession (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/webdriver.js:337:12)
    at Driver (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/chrome.js:778:38)
    at Builder.build (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/builder.js:464:16)
    at Object.start (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/lib/index.js:139:4)
    at Object.<anonymous> (/home/travis/build/tastejs/todomvc/tests/memory.js:15:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
From: Task: WebDriver.navigate().to(http://localhost:8000/examples/knockout-spa/index.html)
    at Driver.schedule (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/webdriver.js:386:17)
    at Navigation.to (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/webdriver.js:1029:25)
    at Driver.get (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/webdriver.js:797:28)
    at setup (/home/travis/build/tastejs/todomvc/tests/memory.js:48:11)
    at TaskQueue.execute_ (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/promise.js:2868:14)
    at TaskQueue.executeNext_ (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/promise.js:2851:21)
    at asyncRun (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/promise.js:2730:27)
    at /home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: <anonymous>
    at executeInFlow (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/lib/index.js:9:24)
    at Object.flow (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/lib/index.js:91:3)
    at /home/travis/build/tastejs/todomvc/tests/memory.js:45:8
    at Array.forEach (native)
    at Object.<anonymous> (/home/travis/build/tastejs/todomvc/tests/memory.js:44:6)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
The command "./test-runner.sh" exited with 123.
cache.2
store build cache
0.00s
6.96schange detected (content changed, file is created, or file is deleted):
/home/travis/build/tastejs/todomvc/tests/node_modules/abbrev/abbrev.js
/home/travis/build/tastejs/todomvc/tests/node_modules/abbrev/LICENSE
/home/travis/build/tastejs/todomvc/tests/node_modules/abbrev/package.json
/home/travis/build/tastejs/todomvc/tests/node_modules/abbrev/README.md
/home/travis/build/tastejs/todomvc/tests/node_modules/adm-zip/adm-zip.js
/home/travis/build/tastejs/todomvc/tests/node_modules/adm-zip/headers/entryHeader.js
/home/travis/build/tastejs/todomvc/tests/node_modules/adm-zip/headers/index.js
/home/travis/build/tastejs/todomvc/tests/node_modules/adm-zip/headers/mainHeader.js
/home/travis/build/tastejs/todomvc/tests/node_modules/adm-zip/methods/deflater.js
/home/travis/build/tastejs/todomvc/tests/node_modules/adm-zip/methods/index.js
/home/travis/build/tastejs/todomvc/tests/node_modules/adm-zip/methods/inflater.js
/home/travis/build/tastejs/todomvc/tests/node_modules/adm-zip/package.json
/home/travis/build/tastejs/todomvc/tests/node_modules/adm-zip/README.md
/home
...
changes detected, packing new archive
uploading archive
Done. Your build exited with 1.
```

**Comment by arthurvr** [comment]
Thanks for the report!

The normal Travis builds (and the site deploys) [seem to work fine atm](https://travis-ci.org/tastejs/todomvc/builds). Let's evaluate the failures on PRs on a case-by-case basis as those are generally related to one specific app.
