### ISSUE TITLE
pipeline is probably proken

### ISSUE THREAD

**Issue by vitalydmitriev1970** [tastejs/todomvc#1852]
TypeError: Cannot read property 'message' of undefined
    at /home/travis/build/tastejs/todomvc/tests/node_modules/drool/lib/index.js:40:28
    at ManagedPromise.invokeCallback_ (/home/travis/build/tastejs/todomvc/tests/node_modules/drool/node_modules/selenium-webdriver/lib/promise.js:1343:14)

**Comment by bernard-lin** [comment]
This is a duplicate of #1825 and can be closed
